zuul:
  routes:
    student:
      path: /users/**
      url: http://localhost:8090/users
    quarkus:
      path: /hello/**
      url: http://localhost:8085/hello
    dotnet:
      path: /dotnet/**
      url: http://localhost:5000/dotnet